COMMON: &common
  # 配置
  work_dir: "F:\\work"
  edu_dir: "F:\\now2"
  mooc_url: "https://www.icourse163.org/home.htm?userId=1031814224"
  work_url: "http://task.ngrok.groupinno.com/"
  # work_url: "http://20.30.1.119:7001/"


CX1: &cx1
  # 配置继承common
  << : *common
  name: "cx1"
